plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/lucaspc3/Desktop/Project Organizer/ledgeman-admin"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]